services:
  plex-proxy:
    container_name: plex-proxy
    network_mode: bridge
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - '5000:5000'
    environment:
      USERNAME: "CHANGEME"
      PASSWORD: "CHANGEME"